spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  main:
    web-application-type: servlet
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          import_files: import_master_country.sql, import_master_title.sql, import_master_user_role.sql, import_master_user_status.sql, import_master_user.sql
  security:
    user:
      name: citius
      password: citiusPassword
      roles: USER
management:
  endpoints:
    web:
      base-path: /status
  server:
    port: 8081
server:
  servlet:
    context-path: 
  port: 8001
  max-http-header-size: 10000000